language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      # from https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
      dist: xenial
      env: TOXENV=py37
      sudo: true

install:
    - travis_retry pip install tox
script:
    - tox
after_success:
    - COVERAGE_ENV=$TOXENV tox -e codecov

# https://docs.travis-ci.com/user/reference/overview/#Container-based
sudo: false
